version: "3"
services:
  storybook:
    image: velo.gl
    build: .
    volumes:
      - ".:/app:rw"
    ports:
      - "6006:6006"
    healthcheck:
      test: curl --fail http://localhost:6006/
  test-storybook:
    image: velo.gl
    volumes:
      - /app/node_modules
      - ".:/app:ro"
    depends_on:
      storybook:
        condition: service_healthy
    command: >
      sh -c "npm ci && npx playwright install-deps
      && npm run test:storybook -- --url http://storybook:6006/"
