version: "3"

services:
    storybook:
        image: node:bookworm
        user: node
        working_dir: /home/node/velo.gl
        environment:
            - MAPTILER_API_KEY
            - VITE_MAPTILER_API_KEY
        volumes:
            - ".:/home/node/velo.gl:rw"
        ports:
            - "6006:6006"
        healthcheck:
            test: curl --fail http://localhost:6006/
        command: >
            sh -c "VITE_COVERAGE=false npm run storybook -- --no-open"

    storybook-coverage:
        image: node:bookworm
        user: node
        working_dir: /home/node/velo.gl
        environment:
            - MAPTILER_API_KEY
            - VITE_MAPTILER_API_KEY
        volumes:
            - ".:/home/node/velo.gl:rw"
        ports:
            - "6006:6006"
        healthcheck:
            test: curl --fail http://localhost:6006/
        command: >
            sh -c "npm run storybook -- --no-open"

    test-storybook:
        image: mcr.microsoft.com/playwright:v1.49.1-noble
        volumes:
            - ".:/home/ubuntu/velo.gl:rw"
        working_dir: /home/ubuntu/velo.gl
        user: ubuntu
        depends_on:
            storybook-coverage:
                condition: service_healthy
        command: >
            sh -c "npm run test:storybook -- --ci --url http://storybook-coverage:6006/ --coverage --browsers chromium,webkit --failOnConsole"

    test-storybook-update:
        image: velo.gl-test-storybook
        build: ./config/test-storybook
        volumes:
            - ".:/app:rw"
            - "./__snapshots__:/app/__snapshots__:rw"
            - type: tmpfs
              target: /app/.cache
        working_dir: /app
        user: ubuntu
        depends_on:
            storybook:
                condition: service_healthy
        command: >
            sh -c "npm run test:storybook -- --updateSnapshot --url http://storybook:6006/ --browsers chromium,webkit"

    storybook-github:
        image: velo.gl-storybook
        build: .
        environment:
            - MAPTILER_API_KEY
            - VITE_MAPTILER_API_KEY
        volumes:
            - ".:/app:rw"
        ports:
            - "6006:6006"
        healthcheck:
            test: curl --fail http://localhost:6006/
        command: >
            sh -c "npm run storybook -- --no-open"

    test-storybook-github:
        image: velo.gl-test-storybook
        build: ./config/test-storybook
        volumes:
            - ".:/app:rw"
        working_dir: /app
        user: root
        depends_on:
            storybook-github:
                condition: service_healthy
        command: >
            sh -c "npm run test:storybook -- --ci --url http://storybook-github:6006/ --coverage --browsers chromium,webkit --failOnConsole"

    sandbox-read-only:
        image: node:bookworm
        user: node
        volumes:
            - ".:/home/node/velo.gl:ro"
        working_dir: /home/node/velo.gl

    sandbox:
        image: node:bookworm
        user: node
        volumes:
            - ".:/home/node/velo.gl:rw"
        working_dir: /home/node/velo.gl
