version: "3"
services:
    storybook:
        image: velo.gl-storybook
        build: .
        volumes:
            - ".:/app:rw"
        ports:
            - "6006:6006"
        healthcheck:
            test: curl --fail http://localhost:6006/
        command: >
            sh -c "npm run storybook -- --no-open"
    test-storybook:
        image: velo.gl-test-storybook
        build: ./config/test-storybook
        volumes:
            - ".:/app:rw"
              #- "./__snapshots__:/app/__snapshots__:rw"
        #working_dir: /app
        user: ubuntu
        depends_on:
            storybook:
                condition: service_healthy
        command: >
            sh -c "npm run test:storybook -- --ci --url http://storybook:6006/"
    test-storybook-update:
        image: velo.gl-test-storybook
        build: ./config/test-storybook
        volumes:
            - ".:/app:ro"
            - "./__snapshots__:/app/__snapshots__:rw"
        working_dir: /app
        user: ubuntu
        depends_on:
            storybook:
                condition: service_healthy
        command: >
            sh -c "npm run test:storybook -- --updateSnapshot --url http://storybook:6006/"

