#FROM node:bookworm
FROM mcr.microsoft.com/playwright:v1.48.2-noble

#RUN apt-get update \
#&& apt-get upgrade -y \
#&& apt-get install -y node-typescript nodejs
#RUN apt-get update \
#&& apt-get -y install ts-node

RUN mkdir /app
WORKDIR /app

