name: Build Storybook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run build

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install docker compose
        run: sudo apt-get -y install docker-compose

      - name: Install dependencies
        run: npm ci

      - name: Storybook visual tests
        env:
          VITE_MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
        run: npm run docker:compose:test:github

