name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        env:
          VITE_MAPTILER_API_KEY: ${{secrets.VITE_MAPTILER_API_KEY}}
        run: npm run build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static

  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
